### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by Silvenga**
Setting up CI/CD.

### CODE REVIEW

**Comment by Silvenga** [comment]
I don't think I can fully setup Appveyor- since Appveyor needs to configure some settings (like push hooks). However, I think I've got most of the infrastructure in-place.

@statianzo if you could, can you:

1. Login into AppVeyor and login via Github (https://ci.appveyor.com/login).
2. Create a new project in AppVeyor targeting Fleck (https://ci.appveyor.com/projects/new)
3. Create a new release environment (https://ci.appveyor.com/environments/new) using the `Nuget` Provider. Use your Fleck nuget.org API key.

So with the settings provided with `appveyor.yml` file, Appveyor will restore, build, test, and pack Fleck. When a build succeeds you can use the Deploy button to push the created nuget package to nuget.org.
Builds will use Appveyor's versioning unless the build was started via a tag push (in which case the version will equal the tag's name).

A side note, I think the `Rakefile` and everything in the support directory can be replace with the `dotnet` commands in all environments (i.e. xbuild has been replace with msbuild, msbuild is now under .NetCore).

**Comment by statianzo** [comment]
Success: https://ci.appveyor.com/project/statianzo/fleck/build/0.0.2-ci

**Comment by statianzo** [comment]
Running into an issue with tagged builds:

```
Build started
if ($env:appveyor_repo_tag -eq 'true') {
    $tag = $env:appveyor_repo_tag_name
    Update-AppveyorBuild -Version "$tag"
}
Update-AppveyorBuild : The term 'Update-AppveyorBuild' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\appveyor\AppData\Local\Temp\1\2jb50u88m1.ps1:5 char:5
+     Update-AppveyorBuild -Version "$tag"
+     ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Update-AppveyorBuild:String) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : CommandNotFoundException
 
Command exited with code 1
```

https://ci.appveyor.com/project/statianzo/fleck/build/0.0.9-ci

**Comment by statianzo** [comment]
Thanks for the fix @Silvenga. I built 1.0.2 successfully. Deployed it to Nuget.

**Pull request merged**
