### PR TITLE
Add net40 support

### PR DESCRIPTION
**Pull request by darkl**
@statianzo, I made the changes you suggested in #259 to @YohskDista's branch.

### CODE REVIEW

**Comment by statianzo** [comment]
Looks great, @darkl. Thanks for cleaning it up.

@YohskDista, does this work for you? AppVeyor built a nuget package artifact you can test out:

https://ci.appveyor.com/project/statianzo/fleck/builds/23201779/artifacts

**Comment by YohskDista** [comment]
I think also that is better and more clean than before @darkl.

@statianzo I will try it tomorrow but I think it should work. I let you know as soon as possible.

Thank you very much guys !

**Comment by YohskDista** [comment]
I just tried the new functionality and it is working just fine. I think you can make a version with this new feature.

@darkl Do you want to develop the support for this feature by yourself or should I do this to help you ? If that's the case then could you explain me how do you think we include this feature ? Should I put a new element in the constructor or do you want test the Windows OS version system ?

**Comment by darkl** [comment]
@YohskDista I think you can create a pull request.
Just introduce a new parameter to the constructors of [`FleckWebSocketTransport`](https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/Default/WampSharp.Fleck/Fleck/FleckWebSocketTransport.cs) and [`AuthenticatedFleckWebSocketTransport`](https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/Default/WampSharp.Fleck/Fleck/FleckAuthenticatedWebSocketTransport.cs), with a backward compatible default value.

Elad

**Comment by YohskDista** [comment]
@darkl I also need to change the `DefaultWampAuthenticationHost` and the `DefaultWampHost` in the `WampSharp.Default.Router` library otherwise I cannot pass the support dual stack value to the `FleckAuthenticatedWebSocketTransport`

**Comment by darkl** [comment]
@YohskDista you can change these too. This is not necessary, since you can also call `host.RegisterTransport` yourself, but we've done it to previously added parameters so I guess it is fine to do this to this parameter as well.

Elad

**Comment by YohskDista** [comment]
@darkl For me it is completely equal. I can also let the user do the `host.RegisterTransport`, it is not a parameter that is set a lot of time and it would be a pity if we add another parameter to all the constructors of `DefaultWampAuthenticationHost` and `DefaultWampHost`.
I think your idea is a bette choice, I didn't know for this method `RegisterTransport`.

@statianzo Do you want me to close my other Pull Request since this one will be accepted ?

**Comment by statianzo** [comment]
Released 1.1.0

Thanks for the help @YohskDista and @darkl 

https://www.nuget.org/packages/Fleck/1.1.0

**Comment by YohskDista** [comment]
Thank you both for your quick answers and your availability !

Leonardo

**Pull request merged**
