### PR TITLE
Always set ReuseAddress

### LINKED ISSUE #292: Set SocketOptionName.ReuseAddress on Linux too
Right now its only set for Windows for some reason:
https://github.com/statianzo/Fleck/blob/2f5365ed229030d0c62b08dd511b9e7da3eb68c3/src/Fleck/WebSocketServer.cs#L31-L36

Running on Linux under .NET Core, I get "already in use" after restarting the app due to TIME_WAIT connections.

`ISocket` does not expose `SetSocketOption`, so I can't do it myself.

### PR DESCRIPTION
**Pull request by xPaw**
Fixes #292

### CODE REVIEW

**Comment by statianzo** [comment]
Seems good to me.

@darkl @AdrianBathurst any concerns with this?

**Comment by darkl** [comment]
Looks good to me, seems like [I accidentally broke it](https://github.com/statianzo/Fleck/commit/2f5365ed229030d0c62b08dd511b9e7da3eb68c3#diff-a401ba6832a2a0bfbaf65cf0cb1da452). I think I didn't realize the `!` in the original `!RuntimeInformation.IsOSPlatform(OSPlatform.Windows)`.

I don't understand why was that check included at first place, as it seems to work fine on Windows nowadays.

Elad

**Comment by darkl** [comment]
Oh, it seems that this change breaks the `SupportsDualStack` switch. @xPaw can you please move the `SetOptions` line back into `SupportsDualStack` if?

**Comment by xPaw** [comment]
Why is reuse related to dual stack?

**Comment by darkl** [comment]
This is the [original issue](https://github.com/statianzo/Fleck/pull/259). I guess you are right and it is not related. This breaks some previous behavior (the reuse was applied on Windows only if the flag`SupportDualStack` was true), but I guess it is ok.

**Pull request merged**
