### PR TITLE
Allow change default keep alive settings to run on Windows only

### PR DESCRIPTION
**Pull request by quynh-ng**
The method "Socket.IOControl" is only available on Windows platform, we need to check before using its.

### CODE REVIEW

**Comment by darkl** [comment]
Hi @statianzo, @Silvenga,
This change is important in order to allow Fleck to run over Unix based systems, as the method [Socket.IOControl](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.iocontrol?view=netframework-4.7.1#System_Net_Sockets_Socket_IOControl_System_Net_Sockets_IOControlCode_System_Byte___System_Byte___) is Windows specific.

The build fails but it has completely nothing to do with this pull request. @Silvenga put an IgnoreAttribute above the failing tests with an Until = "2018-04-29" property, and that date has already passed.

Please pay attention to this pull request and consider merging it.

Thanks
Elad

**Comment by statianzo** [comment]
Thanks for the reminder @darkl 
@quynh-ng if you could make those failing tests into just Ignore without until. I can get this merged and a new version released

**Comment by Silvenga** [comment]
I was concerned with how reliable the portability analyzer was when I started the port (it recorded 100% compatibility), I guess it turns out it doesn't check for everything.

@statianzo, are you okay with me updating AppVeyor build to test under Linux as well? https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/

**Comment by statianzo** [comment]
> @statianzo, are you okay with me updating AppVeyor build to test under Linux as well? 

Of course. That sounds like a useful environment to test on.

**Comment by quynh-ng** [comment]
I ran the test on Ubuntu Linux and macOS High Sierra, the test fails with some reasons, when I looked at the results, I found 2 reasons that related to the runtime:

1. SocketWarpper.cs - line 51 => socket.IOControl(...): System.PlatformNotSupportedException : Socket.IOControl handles Windows-specific control codes and is not supported on this platform.

2. WebSocketServer.cs - line 28 => socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);
- Linux: System.Net.Sockets.SocketException : Protocol not available
- macOS: System.Net.Sockets.SocketException : Invalid argument

And I really don't known why the build is failed.

What should I really need to do?
Do I need to re-create other pull request?

**Comment by quynh-ng** [comment]
@darkl Thanks Elad.

Two ignore test are pass, but still got error on build:

Fleck.Tests.WebSocketServerTests.ShouldSupportDualStackListenWhenServerV6All
System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:8000
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at Fleck.Tests.WebSocketServerTests.ShouldSupportDualStackListenWhenServerV6All()

I don't get it...

**Comment by statianzo** [comment]
Nice work on getting the build green again. Can the change can be done without replacing spaces with tabs? It's difficult to tell what was actually changed in the git history and looks like a whole file rewrite.

**Comment by quynh-ng** [comment]
I think the file is reformated by Visual Studio.

Here my update, only 2 files just 10 lines of code

*SocketWrapper.cs*:

**Line 10**: using System.Runtime.InteropServices;

**Line 65 - 70**:

SetKeepAlive(socket, KeepAliveInterval, RetryInterval);

===>

#if NET45

			SetKeepAlive(socket, KeepAliveInterval, RetryInterval);

#else

			if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))

				SetKeepAlive(socket, KeepAliveInterval, RetryInterval);

#endif

*WebSocketServer.cs*:

**Line 8**: using System.Runtime.InteropServices;

**Line 29 - 30**:

#else

	socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);

==>

#elif !NET45

				if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))

					socket.SetSocketOption(SocketOptionLevel.IPv6, SocketOptionName.IPv6Only, false);

**Comment by darkl** [comment]
@statianzo I made the described changes in #233.

Elad

**Comment by statianzo** [comment]
Merged #233. Thank you for the help @quynh-ng!

**Comment by statianzo** [comment]
Released on NuGet as [1.0.3](https://www.nuget.org/packages/Fleck/1.0.3)

**Pull request closed without merging**
