### PR TITLE
Fix mono always using port 80 and 443

### PR DESCRIPTION
**Pull request by jespertheend**
I updated mono to 5.2.0 just now and it broke Fleck. `Uri.Port` now seems to default to 80 or 443 depending on the protocol. I'm not sure what's the best way to fix this, but since I'm not using port numbers in my uri anyway, this worked for me.

Also, after one year I still don't know how github works. So it seems to have included my change from one year ago.

### CODE REVIEW

**Comment by statianzo** [comment]
Specify your port in your url `new WebSocketServer("wss://yourdomain.com:12345")`

**Comment by jespertheend** [comment]
Hah, of course. It makes the port argument a bit useless then, but that's fine I guess.

**Comment by statianzo** [comment]
Agreed. It's legacy from before the location was parsed as a uri. It should probably get removed.

**Comment by jespertheend** [comment]
Alright, I removed it in #203

**Pull request closed without merging**
