### PR TITLE
Server side queue limit

### PR DESCRIPTION
**Pull request by RenaudGelai**
#265

### CODE REVIEW

**Review by statianzo — COMMENTED** [review]
Rather than it being nullable, I would opt for a default size. Maybe 5MB in queue. Other than that, this seems fine to me.

@darkl Any thoughts on this?

**Comment by RenaudGelai** [comment]
I implemented it so that it doesn't alter the current behavior without explicitly specifying it, this way, people can simply update without worrying.

**Comment by statianzo** [comment]
> I implemented it so that it doesn't alter the current behavior without explicitly specifying it, this way, people can simply update without worrying.

I'll release it as a major version bump to indicate possible breaking behavior.

**Comment by RenaudGelai** [comment]
So, you want me to change to a default 5Mb limit ?

**Comment by darkl** [comment]
I know I'm pretty late here, but I would rather use a `BlockingCollection` than throw away the messages in this case.

**Comment by statianzo** [comment]
> I know I'm pretty late here, but I would rather using a `BlockingCollection` than throwing away the messages in this case.

That would allow slow clients to use up the threadpool, giving the same resource exhaustion issue Fleck has (#265), just with threads instead of memory.

**Comment by RenaudGelai** [comment]
> I know I'm pretty late here, but I would rather using a `BlockingCollection` than throwing away the messages in this case.

It's not throwing away the messages, it's closing the connexion because the client can't keep up, it's a pretty common mechanism in network communications.

**Comment by Muny** [comment]
Any news on this being merged?

**Comment by RenaudGelai** [comment]
Just to let you know, i forked and deployed this in production, it works well, and i don't have memory issues anymore.

**Comment by Muny** [comment]
Thanks for the update Renaud.

 I tried this, but unfortunately it doesn't work for my application. I'm still narrowing down the issue I'm having, but so far it seems that when clients using smartphones connect to my Fleck server, then leave the web page (without closing it) the connection is left open. This is expected. However, the connection never seems to close, even when the device goes offline. This makes the messages the server sends (every 10ms or so) pile up and significantly increase memory usage.

**Comment by RenaudGelai** [comment]
You used the code i changed in the PR ?

**Comment by Muny** [comment]
> You used the code i changed in the PR ?

Yes. I solved the problem by enforcing a heartbeat to be sent by the client. If the client stops sending heartbeats, the server closes the connection.

**Pull request closed without merging**
